### ISSUE TITLE
Is this client-side only?

### ISSUE THREAD

**Issue by timelady-victorious** [necessary129/minecraft-autotorch#1]

**Comment by necessary129** [comment]
Hello, yes. This is a client only mod. It won't do anything on a server.

**Comment by timelady-victorious** [comment]
Yay! Thank you, I think it would be useful to add this to the desktription

**Comment by necessary129** [comment]
It won't do anything on a server as in, You don't need to install this mod on a server. But it will still autoplace torches in multiplayer.
