### ISSUE TITLE
Keyboard toggle shortcut for on/off

### ISSUE THREAD

**Issue by ghost** [necessary129/minecraft-autotorch#4]
Could you add a keyboard shortcut to enable/disable autotorch?

I primarily use it underground and go to through the menu to turn it off when I hit the surface. It seems like a simpler solution than checking skylight level as you mentioned in issue #3.

**Comment by ghost** [comment]
Just realized that removing the torches from offhand is even simpler, sorry for the noise.

**Comment by nyncral** [comment]
a toggle would be cool, 'cause sometimes I want to have torchs in my offhand but don't place torchs
